version: '2'
services:
  influxdb:
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always
    container_name: influxdb
  telegraf:
    image: telegraf
    restart: always
    container_name: telegraf
    ports:
        - "8125:8125/udp"
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
        - influxdb:influxdb
  grafana:
      image: grafana/grafana
      ports:
        - "3000:3000/tcp"
      container_name: grafana
      depends_on:
        - influxdb
      links:
        - influxdb:influxdb

