apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-server-ingres
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-server
          servicePort: 9090
