apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: peeking-sasquatch-server
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: peeking-sasquatch-server
          servicePort: 80
