apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7880
    targetPort: 8080
  selector:
    app: registration-service

