apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registration-service
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "10%"
      maxSurge: "10%"
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: registration-service
        image: dekstroza/registration-service:1.0.1-SNAPSHOT
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/v1.0.0/healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 3
        env:
        - name: HTTP_PROXY_HOST
          value: "linkerd-linkerd"
        - name: HTTP_PROXY_PORT
          value: "4140"
        - name: TOKEN_SERVICE_URL
          value: "http://token-service/api/v1.0.0"
        - name: USER_SERVICE_URL
          value: "http://user-service/api/v1.0.0"
        ports:
        - name: http-port
          containerPort: 8080

