apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7881
    targetPort: 8080
  selector:
    app: user-service

