apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: docker.io/dekstroza/kafka-monitoring-prometheus
        imagePullPolicy: Always
        env:
        - name: JMX_PORT
          value: "9999"
        - name: JMX_HOST
          value: "kafka"
        - name: HTTP_PORT
          value: "8080"
        - name: JMX_EXPORTER_CONFIG_FILE
          value: "kafka.yml"
        ports:
        - name: http-port
          containerPort: 8080

