swarm:
  io:
    workers:
      default:
        io-threads: 4
        task-max-threads: 32
database:
  connection:
    url: "jdbc:postgresql://localhost:5432/hops-factory"
    username: customer_service_app
    password: 123hopS
zipkin:
  url: "http://localhost:9411/api/v1/spans"
