apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
data:
  config.yaml: |-
    admin:
      port: 9990
    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001
    routers:
    - protocol: http
      dtab: |
        /srv        => /#/io.l5d.k8s/default/http;
        /host       => /srv;
        /svc        => /host;
        /host/token-service => /srv/token-service;
      servers:
      - port: 4140
        ip: 0.0.0.0

