apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7777
    targetPort: 8080
  selector:
    app: customer-service

