apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "10%"
      maxSurge: "10%"
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: dekstroza/customer-service:1.0.1-SNAPSHOT
        resources:
          requests:
            memory: "400Mi"
            cpu: "0.5"
          limits:
            memory: "500Mi"
            cpu: "1"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /customer_service/v1.0.0/healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 3
        env:
        - name: HTTP_PROXY_HOST
          value: linkerd091-linkerd
        - name: HTTP_PROXY_PORT
          value: "4140"
        ports:
        - name: http-port
          containerPort: 8080

