apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-exporter
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: kafka-monitor

