apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - name: http-port
          containerPort: 9411
