swarm:
  bind:
    address: 0.0.0.0
  network:
    socket-binding-groups:
      standard-sockets:
        socket-bindings:
          activemq:
            port: 61616
  messaging-activemq:
    servers:
      default:
        security-enabled: false
        remote-acceptors:
            netty-acceptor:
              socket-binding: activemq
        remote-connectors:
            netty-connector:
              socket-binding: activemq
        http-connectors:
          http-connector:
            socket-binding: http
            endpoint: http-acceptor
        http-acceptors:
          http-acceptor:
            http-listener: default
        jmx-management-enabled: true

