swarm:
  io:
    workers:
      default:
        io-threads: 4
        task-max-threads: 32
  http2:
    enabled: true
  flyway:
        jdbc-user: ${db.user}
        jdbc-password: ${db.user.password}
        jdbc-url: ${flyway.url}
  datasources:
    data-sources:
      CustomerDS:
        connection-url: ${db.url}
        driver-name: postgresql
        user-name: ${db.user}
        password: ${db.user.password}
  ds:
    name: CustomerDS
    connection:
    url: ${db.url}
    username: ${db.user}
    password: ${db.user.password}
  jpa:
    default-datasource: CustomerDS

